CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_usuarios_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    cpf VARCHAR(14),
    telefone VARCHAR(20),
    email VARCHAR(254),
    endereco VARCHAR(500),
    observacoes VARCHAR(2000),
    quantidade_kits INTEGER,
    codigo_rastreio VARCHAR(100),
    codigo_identificacao VARCHAR(100),
    kit_entregue_hoje VARCHAR(255),
    data_saida_estoque VARCHAR(255),
    data_entrega VARCHAR(255),
    data_previsao VARCHAR(255),
    atrasado BOOLEAN,
    data_coleta_processo VARCHAR(255),
    data_coleta_realizada VARCHAR(255),
    data_em_mao_brasil VARCHAR(255),
    data_enviado_espanha VARCHAR(255),
    status_resultado VARCHAR(100),
    resultado VARCHAR(5000),
    etapa VARCHAR(255),
    resultado_exame VARCHAR(255),
    anexo_nome VARCHAR(255),
    anexo_caminho VARCHAR(500),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP,
    CONSTRAINT uk_pacientes_codigo_identificacao UNIQUE (codigo_identificacao)
);

CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    codigo_produto VARCHAR(20) NOT NULL,
    codigo_serie VARCHAR(20) NOT NULL,
    estoque_atual INTEGER DEFAULT 0,
    estoque_minimo INTEGER DEFAULT 5,
    ultima_sequencia INTEGER DEFAULT 0,
    CONSTRAINT uk_produtos_codigo UNIQUE (codigo_produto, codigo_serie)
);

CREATE TABLE IF NOT EXISTS estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_kits INTEGER
);

CREATE TABLE IF NOT EXISTS movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255),
    quantidade INTEGER,
    motivo VARCHAR(255),
    data TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    codigo_gerado VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_itens_pedido_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT fk_itens_pedido_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_username ON usuarios(username);
CREATE INDEX IF NOT EXISTS idx_paciente_codigo_identificacao ON pacientes(codigo_identificacao);
CREATE INDEX IF NOT EXISTS idx_paciente_criado_em ON pacientes(criado_em);
CREATE INDEX IF NOT EXISTS idx_paciente_status_resultado ON pacientes(status_resultado);
CREATE INDEX IF NOT EXISTS idx_movimentacao_data ON movimentacoes_estoque(data);
CREATE INDEX IF NOT EXISTS idx_movimentacao_tipo ON movimentacoes_estoque(tipo);

