CREATE TABLE auditoria_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao VARCHAR(100) NOT NULL,
    recurso VARCHAR(100) NOT NULL,
    recurso_id BIGINT,
    ator VARCHAR(255) NOT NULL,
    ocorrido_em TIMESTAMP NOT NULL,
    motivo VARCHAR(1000)
);

CREATE INDEX idx_auditoria_ocorrido_em ON auditoria_eventos(ocorrido_em);
CREATE INDEX idx_auditoria_recurso ON auditoria_eventos(recurso, recurso_id);