ALTER TABLE pacientes ALTER COLUMN cpf TYPE VARCHAR(512);
ALTER TABLE pacientes ALTER COLUMN telefone TYPE VARCHAR(512);
ALTER TABLE pacientes ALTER COLUMN email TYPE VARCHAR(1024);
ALTER TABLE pacientes ALTER COLUMN endereco TYPE VARCHAR(2048);
ALTER TABLE pacientes ALTER COLUMN observacoes TYPE VARCHAR(8192);
ALTER TABLE pacientes ALTER COLUMN resultado TYPE VARCHAR(16384);