CREATE TABLE IF NOT EXISTS medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    cpf VARCHAR(14),
    crm VARCHAR(30),
    email VARCHAR(254),
    telefone VARCHAR(20),
    especialidade VARCHAR(120),
    estoque_privado BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medico_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade_atual INTEGER NOT NULL DEFAULT 0,
    estoque_minimo INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT fk_medico_estoque_medico FOREIGN KEY (medico_id) REFERENCES medicos(id),
    CONSTRAINT fk_medico_estoque_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT uk_medico_estoque_medico_produto UNIQUE (medico_id, produto_id)
);

CREATE TABLE IF NOT EXISTS lotes_produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    medico_id BIGINT,
    codigo_lote VARCHAR(80) NOT NULL,
    quantidade_entrada INTEGER NOT NULL DEFAULT 0,
    quantidade_disponivel INTEGER NOT NULL DEFAULT 0,
    data_entrada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_validade DATE,
    registrado_por_usuario_id BIGINT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT fk_lotes_produto_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_lotes_produto_medico FOREIGN KEY (medico_id) REFERENCES medicos(id),
    CONSTRAINT fk_lotes_produto_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT uk_lotes_produto_codigo UNIQUE (produto_id, codigo_lote)
);

CREATE TABLE IF NOT EXISTS permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave VARCHAR(120) NOT NULL,
    modulo VARCHAR(120) NOT NULL,
    acao VARCHAR(80) NOT NULL,
    descricao VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_permissoes_chave UNIQUE (chave)
);

CREATE TABLE IF NOT EXISTS usuarios_permissoes (
    usuario_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,
    concedido_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concedido_por_usuario_id BIGINT,
    PRIMARY KEY (usuario_id, permissao_id),
    CONSTRAINT fk_usuarios_permissoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_usuarios_permissoes_permissao FOREIGN KEY (permissao_id) REFERENCES permissoes(id),
    CONSTRAINT fk_usuarios_permissoes_concedido_por FOREIGN KEY (concedido_por_usuario_id) REFERENCES usuarios(id)
);

ALTER TABLE pacientes ADD COLUMN medico_id BIGINT;
ALTER TABLE pacientes ADD CONSTRAINT fk_pacientes_medico FOREIGN KEY (medico_id) REFERENCES medicos(id);

ALTER TABLE movimentacoes_estoque ADD COLUMN produto_id BIGINT;
ALTER TABLE movimentacoes_estoque ADD COLUMN medico_id BIGINT;
ALTER TABLE movimentacoes_estoque ADD COLUMN lote_id BIGINT;
ALTER TABLE movimentacoes_estoque ADD COLUMN usuario_id BIGINT;
ALTER TABLE movimentacoes_estoque ADD COLUMN saldo_anterior INTEGER;
ALTER TABLE movimentacoes_estoque ADD COLUMN saldo_posterior INTEGER;
ALTER TABLE movimentacoes_estoque ADD COLUMN registrado_em TIMESTAMP;

ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_movimentacoes_estoque_produto FOREIGN KEY (produto_id) REFERENCES produtos(id);
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_movimentacoes_estoque_medico FOREIGN KEY (medico_id) REFERENCES medicos(id);
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_movimentacoes_estoque_lote FOREIGN KEY (lote_id) REFERENCES lotes_produto(id);
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_movimentacoes_estoque_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id);

CREATE INDEX IF NOT EXISTS idx_medicos_nome ON medicos(nome);
CREATE INDEX IF NOT EXISTS idx_medicos_cpf ON medicos(cpf);
CREATE INDEX IF NOT EXISTS idx_medico_estoque_medico ON medico_estoque(medico_id);
CREATE INDEX IF NOT EXISTS idx_medico_estoque_produto ON medico_estoque(produto_id);
CREATE INDEX IF NOT EXISTS idx_lotes_produto_produto ON lotes_produto(produto_id);
CREATE INDEX IF NOT EXISTS idx_lotes_produto_medico ON lotes_produto(medico_id);
CREATE INDEX IF NOT EXISTS idx_permissoes_modulo_acao ON permissoes(modulo, acao);
CREATE INDEX IF NOT EXISTS idx_usuarios_permissoes_permissao ON usuarios_permissoes(permissao_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_medico ON pacientes(medico_id);
CREATE INDEX IF NOT EXISTS idx_movimentacao_produto ON movimentacoes_estoque(produto_id);
CREATE INDEX IF NOT EXISTS idx_movimentacao_usuario ON movimentacoes_estoque(usuario_id);
CREATE INDEX IF NOT EXISTS idx_movimentacao_lote ON movimentacoes_estoque(lote_id);
